### ISSUE TITLE
Add a command to "change the access permissions and the special mode flags of file system objects"

### ISSUE THREAD

**Issue by smv1999** [smv1999/pysh#3]
Add a cross-platform command implementation to change the access permissions and the special mode flags of file system objects similar to 'chmod' in Linux.

**Comment by vihar-s1** [comment]
I would like to take this issue under
 SLOP 2.0

**Comment by smv1999** [comment]
Sure @vihar-s1 . You can go ahead !

**Comment by vihar-s1** [comment]
is it supposed to cascade in to assign the permissions to all content for a directory or a sub-directory or just change permissions for the directory only and not its content?

**Comment by smv1999** [comment]
Cascading to assign permissions to all the contents / sub-directory can be done by taking an optional parameter. 

So, the primary function would be to change permissions only for the directory. But you can take an additional parameter / flag to do the task recursively for the sub-directories too.
